"""empty message

Revision ID: 499a8fcdf937
Revises: 
Create Date: 2021-02-01 21:05:05.165646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499a8fcdf937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_title'), 'team', ['title'], unique=True)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_title'), 'tournaments', ['title'], unique=True)
    op.create_table('tournaments_teams',
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments_teams')
    op.drop_index(op.f('ix_tournaments_title'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_team_title'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
